"use strict";
const userName = "Anji";
let age = 20;
const email = "anji@gmail.com";
const isSubscribed = true;
let city = "Bangalore";
let loginCount = 3;
age++;
const profileMessage = `Hello ${userName}, you are ${age} years old and your email is ${email}`;
const isAdult = age >= 18;
const isEligibleForPremium = age > 18 && isSubscribed;
const hasFrequentLogin = loginCount > 2;
console.log("----- User Details -----");
console.log("Name:", userName);
console.log("Age:", age);
console.log("Email:", email);
console.log("Subscribed:", isSubscribed);
console.log("\n----- Inferred Variables -----");
console.log("City:", city);
console.log("Login Count:", loginCount);
console.log("\n----- Profile Message -----");
console.log(profileMessage);
console.log("\n----- Conditions -----");
console.log("Is Adult:", isAdult);
console.log("Eligible for Premium:", isEligibleForPremium);
console.log("Frequent User:", hasFrequentLogin);
